runtime: nodejs12

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'apartmany-astrid-sql'
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: '2%&S2i7ZUy'
  INSTANCE_CONNECTION_NAME: 'apartmany-astrid-admin:europe-west3:apartmany-astrid'

beta_settings:
  cloud_sql_instances: 'apartmany-astrid-admin:europe-west3:apartmany-astrid'
